# Generated by Django 3.0.5 on 2020-04-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllInfo',
            fields=[
                ('lottieid', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('lottie', models.CharField(max_length=100, verbose_name='动图URL')),
                ('userimg', models.CharField(max_length=100, verbose_name='用户头像')),
                ('username', models.CharField(max_length=50, verbose_name='用户昵称')),
                ('type', models.CharField(max_length=20, verbose_name='所属类别')),
            ],
            options={
                'verbose_name': '图片URL数据',
                'verbose_name_plural': '图片URL数据',
            },
        ),
    ]
